[package]
name = "assign-server"
version = "0.1.0"
authors = ["Regan-Koopmans <regankoopmans@protonmail.com>"]

[dependencies]
json = "0.11.6"
urlparse = "0.7.3"

[dependencies.url]
git = "https://github.com/servo/rust-url"